CREATE TABLE professors (
    id INT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    department VARCHAR(255) NOT NULL,
    field_of_expertise VARCHAR(255) NOT NULL,
    years_of_experience INT NOT NULL,
    education VARCHAR(255) NOT NULL,
    date_applied TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO professors (first_name, last_name, email, department, field_of_expertise, years_of_experience, education) VALUES
('John', 'Doe', 'john.doe@email.com', 'Computer Science', 'Artificial Intelligence', 5, 'PhD in Computer Science'),
('Jane', 'Smith', 'jane.smith@email.com', 'Mathematics', 'Applied Mathematics', 8, 'PhD in Mathematics'),
('William', 'Brown', 'william.brown@email.com', 'Physics', 'Quantum Mechanics', 10, 'PhD in Physics'),
('Olivia', 'Johnson', 'olivia.johnson@email.com', 'Biology', 'Genetics', 4, 'PhD in Biology'),
('David', 'Davis', 'david.davis@email.com', 'History', 'Ancient Civilizations', 12, 'PhD in History'),
('Sophia', 'Miller', 'sophia.miller@email.com', 'Chemistry', 'Organic Chemistry', 7, 'PhD in Chemistry'),
('James', 'Wilson', 'james.wilson@email.com', 'Engineering', 'Electrical Engineering', 6, 'PhD in Engineering'),
('Mia', 'Moore', 'mia.moore@email.com', 'Economics', 'Macroeconomics', 9, 'PhD in Economics'),
('Benjamin', 'Taylor', 'benjamin.taylor@email.com', 'Sociology', 'Urban Sociology', 11, 'PhD in Sociology'),
('Charlotte', 'Anderson', 'charlotte.anderson@email.com', 'Literature', '19th Century Literature', 13, 'PhD in Literature'),
('Lucas', 'Thomas', 'lucas.thomas@email.com', 'Political Science', 'Public Policy', 15, 'PhD in Political Science'),
('Amelia', 'Jackson', 'amelia.jackson@email.com', 'Law', 'International Law', 6, 'Juris Doctor'),
('Ethan', 'White', 'ethan.white@email.com', 'Psychology', 'Cognitive Psychology', 10, 'PhD in Psychology'),
('Harper', 'Harris', 'harper.harris@email.com', 'Philosophy', 'Ethics', 8, 'PhD in Philosophy'),
('Alexander', 'Martin', 'alexander.martin@email.com', 'Physics', 'Astrophysics', 5, 'PhD in Physics'),
('Ella', 'Garcia', 'ella.garcia@email.com', 'Anthropology', 'Cultural Anthropology', 7, 'PhD in Anthropology'),
('Jack', 'Rodriguez', 'jack.rodriguez@email.com', 'Engineering', 'Mechanical Engineering', 12, 'PhD in Engineering'),
('Chloe', 'Lopez', 'chloe.lopez@email.com', 'Education', 'Curriculum Development', 9, 'PhD in Education'),
('Daniel', 'Gonzalez', 'daniel.gonzalez@email.com', 'Music', 'Music Theory', 11, 'PhD in Music'),
('Grace', 'Perez', 'grace.perez@email.com', 'Sociology', 'Criminal Justice', 4, 'PhD in Sociology'),
('Henry', 'Martinez', 'henry.martinez@email.com', 'Political Science', 'Global Politics', 8, 'PhD in Political Science'),
('Mason', 'Roberts', 'mason.roberts@email.com', 'History', 'Modern European History', 14, 'PhD in History'),
('Ava', 'Walker', 'ava.walker@email.com', 'Psychology', 'Developmental Psychology', 5, 'PhD in Psychology'),
('Sebastian', 'Scott', 'sebastian.scott@email.com', 'Mathematics', 'Statistics', 9, 'PhD in Mathematics'),
('Lily', 'Young', 'lily.young@email.com', 'Sociology', 'Social Movements', 6, 'PhD in Sociology'),
('Samuel', 'King', 'samuel.king@email.com', 'Economics', 'Behavioral Economics', 12, 'PhD in Economics'),
('Evelyn', 'Wright', 'evelyn.wright@email.com', 'Literature', 'Shakespearean Studies', 7, 'PhD in Literature'),
('Wyatt', 'Lopez', 'wyatt.lopez@email.com', 'Biology', 'Ecology', 4, 'PhD in Biology'),
('Harper', 'Bennett', 'harper.bennett@email.com', 'Geography', 'Urban Planning', 10, 'PhD in Geography'),
('Elijah', 'Carter', 'elijah.carter@email.com', 'Education', 'Special Education', 5, 'PhD in Education'),
('Scarlett', 'Mitchell', 'scarlett.mitchell@email.com', 'Art History', 'Renaissance Art', 7, 'PhD in Art History'),
('Levi', 'Adams', 'levi.adams@email.com', 'Mathematics', 'Mathematical Logic', 8, 'PhD in Mathematics'),
('Isabella', 'Nelson', 'isabella.nelson@email.com', 'History', 'Medieval History', 11, 'PhD in History'),
('Jack', 'Hernandez', 'jack.hernandez@email.com', 'Physics', 'Particle Physics', 9, 'PhD in Physics'),
('Archer', 'Perez', 'archer.perez@email.com', 'Chemistry', 'Biochemistry', 12, 'PhD in Chemistry'),
('Lila', 'Robinson', 'lila.robinson@email.com', 'Computer Science', 'Cybersecurity', 7, 'PhD in Computer Science'),
('Henry', 'Murphy', 'henry.murphy@email.com', 'Philosophy', 'Political Philosophy', 10, 'PhD in Philosophy'),
('Nora', 'Cook', 'nora.cook@email.com', 'Law', 'Constitutional Law', 8, 'Juris Doctor');